replicaCount: 1  

image:
  repository: bibigul28/web  
  tag: "v1.0.1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

env:
  API_URL: "http://api-api:3001"  

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

probes:
  path: /health  