apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: {{ .Values.service.port }}
  selector:
    app: web