---
- name: Install dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Docker GPG key
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  args:
    warn: false

- name: Add Docker repository
  copy:
    content: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker with supported version for RKE
  apt:
    name:
      - "docker-ce=5:20.10.24~3-0~ubuntu-jammy"
      - "docker-ce-cli=5:20.10.24~3-0~ubuntu-jammy"
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    force: yes


- name: Hold Docker packages to prevent automatic updates
  shell: |
    apt-mark hold docker-ce docker-ce-cli containerd.io

